import { ApiProperty, ApiPropertyOptional } from "@nestjs/swagger";
import { IsNotEmpty, IsOptional, IsString, Length } from "class-validator";

export class EnableMfaDto {
  @ApiProperty({
    example: "123456",
    description: "6-digit TOTP code generated by authenticator app",
  })
  @IsString()
  @IsNotEmpty()
  @Length(6, 6, { message: "TOTP code must be 6 digits" })
  totpCode!: string;
}

export class VerifyMfaLoginDto {
  @ApiProperty({ description: "Temporary 2FA token returned during login" })
  @IsString()
  @IsNotEmpty()
  mfaToken!: string;

  @ApiPropertyOptional({ example: "123456", description: "6-digit TOTP code" })
  @IsOptional()
  @IsString()
  totpCode?: string;

  @ApiPropertyOptional({
    example: "ABCD-1234-EFGH",
    description: "Single-use backup recovery code",
  })
  @IsOptional()
  @IsString()
  recoveryCode?: string;
}

export class DisableMfaDto {
  @ApiProperty({ description: "User account password" })
  @IsString()
  @IsNotEmpty()
  password!: string;

  @ApiPropertyOptional({ example: "123456", description: "6-digit TOTP code" })
  @IsOptional()
  @IsString()
  @Length(6, 6, { message: "TOTP code must be 6 digits" })
  totpCode?: string;

  @ApiPropertyOptional({
    example: "ABCD-1234-EFGH",
    description: "Single-use backup recovery code",
  })
  @IsOptional()
  @IsString()
  recoveryCode?: string;
}

export class MfaSecretResponseDto {
  @ApiProperty({
    example: "JBSWY3DPEHPK3PXP",
    description: "Base32 secret key",
  })
  secret!: string;

  @ApiProperty({
    example:
      "otpauth://totp/Allinone:user@example.com?secret=JBSWY3DPEHPK3PXP&issuer=Allinone",
  })
  otpauthUrl!: string;

  @ApiProperty({ example: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA..." })
  qrCodeDataUrl!: string;
}

export class MfaEnableResponseDto {
  @ApiProperty({
    example: ["A1B2-C3D4", "E5F6-G7H8"],
    description: "10 single-use recovery codes (save these securely)",
  })
  recoveryCodes!: string[];
}
